maligadproj1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')) # Path to created view
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('help/', views.help, name='help'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/update', views.update, name='update'),
    path('create/', views.create, name='create'),
]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=100) 
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices') # connect to the class, models.CASCADE
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

polls/forms.py
from django.forms import ModelForm
from .models import Question

class QuestionModelForm(ModelForm):
    class Meta:
        model = Question
        exclude = ['id']

polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Question
from .forms import QuestionModelForm
from datetime import datetime

def index(request): 
    context = {}
    questions = Question.objects.all()
    context['questions'] = questions
    return render(request, 'index.html', context)

def help(request):
    return HttpResponse(request, 'This is the help page.')

def detail(request, question_id):
    context = {}
    context['question'] = Question.objects.get(id=question_id)
    return render(request, 'detail.html', context)

def update(request, question_id):
    context = {}
    question = Question.objects.get(id=question_id)

    if request.method == 'POST':
        form = QuestionModelForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return HttpResponse('Question updated')
        else:
            context['form'] = form
            render(request, 'update.html', context)
    else:
        context['form'] = QuestionModelForm(instance=question)
    return render(request, 'update.html', context)

def create(request):
    context = {}
    form = QuestionModelForm(request.POST)
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('polls:index')
        else:
            context['form'] = form
            return render(request, 'create.html', context)
    else:
        context['form'] = QuestionModelForm(initial={'pub_date': datetime.now()})
        return render(request, 'create.html', context)

polls/templates/base.html
{% load static %}
<html>
    <head>
        <title>
            {% block head %} {% endblock %}
        </title>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/materialize/css/materialize.min.css' %}"></link>
        {% block customcss %} {% endblock %}
    </head>
    <body>
        <nav>
            <div class="nav-wrapper">
            <a href="#" class="brand-logo">Polls</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'polls:index' %}">Home</a></li>
                <li><a href="{% url 'polls:index' %}">Help</a></li>
                <li><a href="#">Test</a></li>
            </ul>
            </div>
        </nav>
        <div class="container">
        {% block body %} {% endblock %}
    <script src="{% static 'polls/materialize/js/materialize.min.js' %}"></script>
    {% block customjs %} {% endblock %}
        </div>
    </body>
</html>

polls/templates/create.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'polls:create' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}
        {% endfor %}
        <input type="submit" value="Create"/>
    </form>
{% endblock %}

polls/templates/detail.html
{% extends 'base.html' %}
{% block head %}
    this is the detail page
{% endblock %}

{% block body %}
    Question: {{ question.question_text }}<br/>
    {% for choice in question.choices.all %}
        {{ choice.choice_text }} | votes: {{ choice.votes }}
    {% endfor %}
{% endblock %}

polls/templates/index.html
{% extends 'base.html' %}
{% block head %}
    this is the index page
{% endblock %}

{% block body %}
    <ol>
    {% for question in questions %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">Question: {{ question.question_text }}</a> <br/>
        </li>
    {% endfor %}
    </ol>
    <div class="container">
        <h1><a href="{% url 'polls:create' %}">CREATE NEW QUESTION</a></h2>
    </div>
{% endblock %}

polls/templates/update.html
{% extends 'base.html' %}
{% block head %}
    this is the update page
{% endblock %}

{% block body %}
    <form action="{% url 'polls:update' form.instance.id %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.errors }}
            {{ field.label }} {{ field }}
        {% endfor %}
        <input type="submit" value="Update"/>
    </form>
{% endblock %}